### ISSUE TITLE
GIF for README.md

### ISSUE THREAD

**Issue by Enteleform** [crash5/CopyWithLineNumbersReloaded#1]
Hey man, nice plugin :grin: 

I just demoed it @ [**This Post**](https://forum.sublimetext.com/t/adding-line-numbers-to-a-list-of-lines/20973/14), here's the GIF in case you want to use it for your `README.md`

![animation 1](https://cloud.githubusercontent.com/assets/10906415/16093611/900cd57c-330a-11e6-8712-5cfe5deb70e6.gif)

**Comment by crash5** [comment]
Hi!

Thank you :)
